/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VehiclesRouteImport } from './routes/vehicles'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LegalPolicyRouteImport } from './routes/legal-policy'
import { Route as HyreEvRouteImport } from './routes/hyre-ev'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogPowerPlusVsRapidRouteImport } from './routes/blog.power-plus-vs-rapid'
import { Route as BlogHomeChargingElectricScooterRouteImport } from './routes/blog.home-charging-electric-scooter'
import { Route as BlogBestElectricScooterHyderabadDailyCommuteRouteImport } from './routes/blog.best-electric-scooter-hyderabad-daily-commute'

const VehiclesRoute = VehiclesRouteImport.update({
  id: '/vehicles',
  path: '/vehicles',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPolicyRoute = LegalPolicyRouteImport.update({
  id: '/legal-policy',
  path: '/legal-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const HyreEvRoute = HyreEvRouteImport.update({
  id: '/hyre-ev',
  path: '/hyre-ev',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogPowerPlusVsRapidRoute = BlogPowerPlusVsRapidRouteImport.update({
  id: '/power-plus-vs-rapid',
  path: '/power-plus-vs-rapid',
  getParentRoute: () => BlogRoute,
} as any)
const BlogHomeChargingElectricScooterRoute =
  BlogHomeChargingElectricScooterRouteImport.update({
    id: '/home-charging-electric-scooter',
    path: '/home-charging-electric-scooter',
    getParentRoute: () => BlogRoute,
  } as any)
const BlogBestElectricScooterHyderabadDailyCommuteRoute =
  BlogBestElectricScooterHyderabadDailyCommuteRouteImport.update({
    id: '/best-electric-scooter-hyderabad-daily-commute',
    path: '/best-electric-scooter-hyderabad-daily-commute',
    getParentRoute: () => BlogRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/hyre-ev': typeof HyreEvRoute
  '/legal-policy': typeof LegalPolicyRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/vehicles': typeof VehiclesRoute
  '/blog/best-electric-scooter-hyderabad-daily-commute': typeof BlogBestElectricScooterHyderabadDailyCommuteRoute
  '/blog/home-charging-electric-scooter': typeof BlogHomeChargingElectricScooterRoute
  '/blog/power-plus-vs-rapid': typeof BlogPowerPlusVsRapidRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/hyre-ev': typeof HyreEvRoute
  '/legal-policy': typeof LegalPolicyRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/vehicles': typeof VehiclesRoute
  '/blog/best-electric-scooter-hyderabad-daily-commute': typeof BlogBestElectricScooterHyderabadDailyCommuteRoute
  '/blog/home-charging-electric-scooter': typeof BlogHomeChargingElectricScooterRoute
  '/blog/power-plus-vs-rapid': typeof BlogPowerPlusVsRapidRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/hyre-ev': typeof HyreEvRoute
  '/legal-policy': typeof LegalPolicyRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/vehicles': typeof VehiclesRoute
  '/blog/best-electric-scooter-hyderabad-daily-commute': typeof BlogBestElectricScooterHyderabadDailyCommuteRoute
  '/blog/home-charging-electric-scooter': typeof BlogHomeChargingElectricScooterRoute
  '/blog/power-plus-vs-rapid': typeof BlogPowerPlusVsRapidRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/hyre-ev'
    | '/legal-policy'
    | '/privacy'
    | '/sitemap.xml'
    | '/vehicles'
    | '/blog/best-electric-scooter-hyderabad-daily-commute'
    | '/blog/home-charging-electric-scooter'
    | '/blog/power-plus-vs-rapid'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/hyre-ev'
    | '/legal-policy'
    | '/privacy'
    | '/sitemap.xml'
    | '/vehicles'
    | '/blog/best-electric-scooter-hyderabad-daily-commute'
    | '/blog/home-charging-electric-scooter'
    | '/blog/power-plus-vs-rapid'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/hyre-ev'
    | '/legal-policy'
    | '/privacy'
    | '/sitemap.xml'
    | '/vehicles'
    | '/blog/best-electric-scooter-hyderabad-daily-commute'
    | '/blog/home-charging-electric-scooter'
    | '/blog/power-plus-vs-rapid'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRouteWithChildren
  ContactRoute: typeof ContactRoute
  HyreEvRoute: typeof HyreEvRoute
  LegalPolicyRoute: typeof LegalPolicyRoute
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  VehiclesRoute: typeof VehiclesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vehicles': {
      id: '/vehicles'
      path: '/vehicles'
      fullPath: '/vehicles'
      preLoaderRoute: typeof VehiclesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal-policy': {
      id: '/legal-policy'
      path: '/legal-policy'
      fullPath: '/legal-policy'
      preLoaderRoute: typeof LegalPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hyre-ev': {
      id: '/hyre-ev'
      path: '/hyre-ev'
      fullPath: '/hyre-ev'
      preLoaderRoute: typeof HyreEvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/power-plus-vs-rapid': {
      id: '/blog/power-plus-vs-rapid'
      path: '/power-plus-vs-rapid'
      fullPath: '/blog/power-plus-vs-rapid'
      preLoaderRoute: typeof BlogPowerPlusVsRapidRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/home-charging-electric-scooter': {
      id: '/blog/home-charging-electric-scooter'
      path: '/home-charging-electric-scooter'
      fullPath: '/blog/home-charging-electric-scooter'
      preLoaderRoute: typeof BlogHomeChargingElectricScooterRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/best-electric-scooter-hyderabad-daily-commute': {
      id: '/blog/best-electric-scooter-hyderabad-daily-commute'
      path: '/best-electric-scooter-hyderabad-daily-commute'
      fullPath: '/blog/best-electric-scooter-hyderabad-daily-commute'
      preLoaderRoute: typeof BlogBestElectricScooterHyderabadDailyCommuteRouteImport
      parentRoute: typeof BlogRoute
    }
  }
}

interface BlogRouteChildren {
  BlogBestElectricScooterHyderabadDailyCommuteRoute: typeof BlogBestElectricScooterHyderabadDailyCommuteRoute
  BlogHomeChargingElectricScooterRoute: typeof BlogHomeChargingElectricScooterRoute
  BlogPowerPlusVsRapidRoute: typeof BlogPowerPlusVsRapidRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogBestElectricScooterHyderabadDailyCommuteRoute:
    BlogBestElectricScooterHyderabadDailyCommuteRoute,
  BlogHomeChargingElectricScooterRoute: BlogHomeChargingElectricScooterRoute,
  BlogPowerPlusVsRapidRoute: BlogPowerPlusVsRapidRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRouteWithChildren,
  ContactRoute: ContactRoute,
  HyreEvRoute: HyreEvRoute,
  LegalPolicyRoute: LegalPolicyRoute,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  VehiclesRoute: VehiclesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
